# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Slimefun Builder

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.5.0
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk
          architecture: x64
          cache: maven
      - name: Delete useless folders
        run: |
          rm -rf **/target/
      - name: Build Slimefun
        run: mvn install
      - name: Delete useless files
        run: |
          rm -rf **/target/classes **/target/maven-archiver **/target/maven-status **/target/generated-sources
          rm **/target/original-*.jar
      - name: Setup server
        run: |
          echo 'eula=true' > eula.txt
          mkdir plugins
      - name: Place plugins jar
        run: |
          cp test/target/*.jar plugins/
          cp target/*.jar plugins/
      - uses: actions/upload-artifact@v4
        name: Upload Beta artifact
        with:
          name: Slimefun Beta Build
          path: target

      - name: Download 1.20.4 Paper
        run: |
            VERSION="1.20.4"
            if [ "$VERSION" == "latest" ]; then
              VERSION=$(curl https://api.papermc.io/v2/projects/paper/ -s | jq -r '.versions[-1]')
            fi

            BUILD_JAR=$(curl -s "https://api.papermc.io/v2/projects/paper/versions/$VERSION/builds" \
              | jq '.builds[-1] | "\(.build) \(.downloads.application.name)"' -r)
            BUILD=$(echo "$BUILD_JAR" | awk '{print $1}')
            JAR_FILE=$(echo "$BUILD_JAR" | awk '{print $2}')

            echo "Downloading... https://api.papermc.io/v2/projects/paper/versions/$VERSION/builds/$BUILD/downloads/$JAR_FILE"
            curl -o paper.jar \
              "https://api.papermc.io/v2/projects/paper/versions/$VERSION/builds/$BUILD/downloads/$JAR_FILE"

      - name: Run server
        run: |
          java -jar paper.jar --nogui
