# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Slimefun Builder

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 21
          java-package: jdk
          architecture: x64
          cache: maven
      - name: Build Slimefun
        run: mvn -B package --errors
      - uses: actions/upload-artifact@v2
        name: Upload Beta artifact
        with:
          name: Slimefun Beta Build
          path: staging
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        if: github.ref_name == 'master'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "exp"
          prerelease: true
          title: "Slimefun 自动构建版本"
          files: |
            target/slimefun-*.jar